Add white-list-only flag (#9)

diff --git a/terms-of-service-acceptance/run/action.yml b/terms-of-service-acceptance/run/action.yml
--- a/terms-of-service-acceptance/run/action.yml
+++ b/terms-of-service-acceptance/run/action.yml
@@ -27,12 +27,43 @@ inputs:
     description: 'The token used for Github API requests'
     default: ${{ github.token }}
     required: false
+  white-list-only:
+    description: 'Workflow succeeds only when user (PR submitter or commenter) is whitelisted'
+    default: 'false'
+    required: false
 
 runs:
   using: 'composite'
   steps:
+    - name: Check if contributor assistant has to run
+      id: check-status
+      run: |
+        isCheckRequired=true
+        if [[ "${{ inputs.white-list-only }}" == 'true' ]]; then
+          echo "Skipping Terms of Service acceptance: white list only strategy enabled"
+          isCheckRequired=false
+          currentUser="${{ github.event.pull_request.user.login }}"
+          if [ -z "$currentUser" ]; then
+            currentUser="${{ github.event.issue.user.login }}"
+          fi        
+          if [[ "${{ inputs.white-list }}" =~ (^|.*,)${currentUser}(,.*|$) ]]; then
+            echo "User is white listed"
+          else
+            echo "User is not white listed"
+            exit 1
+          fi
+        else
+          if [ "${{ github.event.comment.body }}" == 'recheck' ] || [ "${{ github.event.comment.body }}" == "${{ inputs.pr-comment-tos-acceptance-request }}" ] || [ "${{ github.event_name }}" == 'pull_request_target' ] || [ "${{ github.event_name }}" == 'pull_request' ]; then
+            echo "Require Terms of Service acceptance: event = ${{ github.event_name }}, comment = ${{ github.event.comment.body }}"
+          else
+            echo "Skipping Terms of Service acceptance: event = ${{ github.event_name }}, comment = ${{ github.event.comment.body }}"
+            isCheckRequired=false
+          fi
+        fi
+        echo "isCheckRequired=$isCheckRequired" >> $GITHUB_OUTPUT
+      shell: bash
     - name: Run Terms of Service acceptance
-      if: (github.event.comment.body == 'recheck' || github.event.comment.body == ${{ inputs.pr-comment-tos-acceptance-request }}) || github.event_name == 'pull_request_target' || github.event_name == 'pull_request'
+      if: ${{ steps.check-status.outputs.isCheckRequired == 'true' }}
       uses: contributor-assistant/github-action@v2.3.0
       env:
         GITHUB_TOKEN: ${{ inputs.github-token }}
